### ISSUE TITLE
引入时报错：TypeError

### ISSUE THREAD

**Issue by TransMux** [FYWinds/gocqapi#1]
具体报错信息如下：
```
Traceback (most recent call last):
  File "E:/python2/QQToVenir/demo.py", line 1, in <module>
    from gocqapi import api
  File "E:\pythonvenv\Nonebot\lib\site-packages\gocqapi\__init__.py", line 3, in <module>
    from .info import InfoAPI
  File "E:\pythonvenv\Nonebot\lib\site-packages\gocqapi\info.py", line 3, in <module>
    from ._api import BaseAPI
  File "E:\pythonvenv\Nonebot\lib\site-packages\gocqapi\_api.py", line 8, in <module>
    class BaseAPI:
  File "E:\pythonvenv\Nonebot\lib\site-packages\gocqapi\_api.py", line 16, in BaseAPI
    async def call(self, api: str, **kwargs: Any) -> dict[Any, Any]:
TypeError: 'type' object is not subscriptable
```

报错代码：
```python
from gocqapi import api
```

**Comment by FYWinds** [comment]
python 版本适配问题
是我的锅不小心写了个3.9+才支持的特性

正在修复中...

**Comment by TransMux** [comment]
哇！好快的回复！我提了个PR，把类型注解删了临时解决了这个问题，麻烦大大看一下哦~

**Comment by FYWinds** [comment]
已修复更新并打包发布

**Comment by TransMux** [comment]
太快了！你太强了，我好爱你，mua~mua~mua~ ヾ(ﾟ∀ﾟゞ)

> 已修复更新并打包发布

**Comment by FYWinds** [comment]
太久没更新了可能会有点年久失修，使用过程中有bug请随时提
